### ISSUE TITLE
Request to add flag for auto-updates of homework set assigned users on LTI launch

### ISSUE THREAD

**Issue by timkato** [ubc/webwork2#14]
UBC ENHC0011356. Request to add a flag for an administrator to disable the auto-updates of visible homework set assigned users when a student launches the LTI (default is to add them to each homework set upon LTI launch from Blackboard or Canvas). Plan is that this can be updated via DB only, to avoid modifying webwork core.

**Comment by andrew-gardener** [comment]
@timkato will be in prod tomorrow morning (added to CHG0041236)

**Comment by timkato** [comment]
Thanks!
