### ISSUE TITLE
LTI grade sync is slow with large amount of courses/students

### ISSUE THREAD

**Issue by xcompass** [ubc/webwork2#21]
Currently, LTI grade sync sends every assignment for every student and it takes about 7.5 hours for LTI to sync all grades for all courses. It takes way too long. 

We need to record the grade changes since last sync and only sync changes.

**Comment by andrew-gardener** [comment]
LTI 1.3 updates should speed this up significantly though it is still only performs one operation at a time. It should be possible to update courses in parallel now as well (though the work to do this hasn't been done)
