### ISSUE TITLE
Improve Sanitization of Canvas Assignment Names

### ISSUE THREAD

**Issue by timkato** [ubc/webwork2#23]
From @andrew-gardener 
its using the same sanitizer as course name https://github.com/ubc/webwork2/blob/ubc/lib/WebworkBridge/Bridges/LTIBridge.pm#L69 & https://github.com/ubc/webwork2/blob/ubc/lib/WebworkBridge/Bridges/LTIBridge.pm#L76
course names don't allow periods because its used in for database tables names
a new sanitizer could be made for the assignment names (though it would cause problems for existing lti links so couldn't be done during the term)
UBC ENHC0011934

**Comment by kitsook** [comment]
Using the course name sanitizer also limits the quiz / assignment name to be 40 (again, because of mysql limitation). ref INC1780885
