### ISSUE TITLE
Online exam answers missing issue

### ISSUE THREAD

**Issue by xcompass** [ubc/webwork2#28]
From one of the instructor

> Some students seem to have lost significant amounts of their work (some reported 50-80% of their work lost). Fortunately the number of affected students remained fairly small but because of the magnitude of the impact this issue seems well worth closer investigations.

> As a lead, the different cases suggest some pattern:
> a) no interaction with WW for extended times (maybe 20-40mins) while students were working on paper.
> b) entering results on WW
> c) upon clicking 'preview answers’ most answers were lost. Answers provided early during the exam seem to survive.
> 
> Based on that, my suspicion is that the autosave feature for WW exams does nothing if no change happened on the page. Subsequently, if enough time elapses, the connection to the WW server possibly times out (but this is not visible to the students). When students then later enter answers and click 'preview answers’ (or the autosave gets triggered) the server does not accept the requests any longer and the WW page gets reloaded with the last results stored on the server, discarding all newly entered data. Given the stress level of an exam I would assume that students may not even notice this and continue with the next question so that the timeout could happen several times and the missing answers are noticed only towards the end of the exam.

> Possibly this has nothing to do with WW and rather with Canvas or Shibboleth because I believe those are responsible for the authentication of students. Maybe it is enough to ensure that the autosave feature is triggered regardless of whether anything was entered, just to keep the credentials of the connection up to date and valid.

> Given the impact on affected students this issue should be investigated and hopefully resolved before the start of the fall term, especially because likely even more courses will use WW for the midterms and final exams than in the spring. I will be the IIC of Math 102 and we will certainly follow the lead of Math 103.

**Comment by kitsook** [comment]
The situation sounds like a session timeout.  But, with quiz autosave enabled (even when there is no user input), there are periodic submissions sent to server as long as students are on the questions page.  So the session shouldn't timeout.

**Comment by xcompass** [comment]
That's what I expect. We probably need to do some testing.

**Comment by andrew-gardener** [comment]
the closest I can reproduce this issue is to have two tabs open on the same quiz version (one with answers and the other all blank). In this situation its possible that a timeout will wipe the current submitted answers and load the preview (which might contain the answers or all blanks based on timing).

I can't seem to trigger this under other circumstances. If the situation was caused by the above then the only real improvements I can think of are:
- only auto safe if inputs changed since last autosave
- and/or don't autosave if all blank

@xcompass is the above good enough for this?

**Comment by xcompass** [comment]
Sounds good to me. Thanks.
