### ISSUE TITLE
When NRPS fails with invalid rlid, all users in the course gets marked as "Dropped"

### ISSUE THREAD

**Issue by ionparticle** [ubc/webwork2#37]
If the resource link got deleted in Canvas, NRPS fails with error message:

`
{"errors":{"type":"bad_request","message":"Invalid 'rlid' parameter"}}
`

It looks like lti_update_classlist.pl is unable to catch this error and continues on to run the course updater with an empty classlist, resulting in Webwork thinking that all previously enrolled users were dropped.

**Comment by andrew-gardener** [comment]
Fixed in https://github.com/ubc/webwork2/commit/0ea8e72f5b60387ec0ebfc05a46d1ee7d10acb40

Not applied to prod (required a db upgrade so safest to do after finals)
